import { Bot, Target, Building2, Briefcase } from 'lucide-react';
import { FeatureCard } from '../cards/FeatureCard';

export function FeaturesSection() {
  const features = [
    {
      icon: Bot,
      title: "AI Skill Analyzer",
      description: "Discover your strengths and get personalized learning paths generated by advanced AI.",
    },
    {
      icon: Target,
      title: "For Students",
      description: "Track your progress, connect with mentors, and land your dream job with data-backed insights.",
    },
    {
      icon: Building2,
      title: "For Universities",
      description: "Monitor placement stats, track alumni success, and improve academic programs with analytics.",
    },
    {
      icon: Briefcase,
      title: "For Employers",
      description: "Find pre-vetted candidates that precisely match your job requirements and company culture.",
    }
  ];

  return (
    <section className="py-24 bg-white">
      <div className="mx-auto max-w-7xl px-6">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold text-slate-900 sm:text-4xl">Platform Highlights</h2>
          <p className="mt-4 text-lg text-slate-600">Everything you need to bridge the gap between education and employment.</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature, idx) => (
            <FeatureCard key={idx} {...feature} />
          ))}
        </div>
      </div>
    </section>
  );
}
